name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때만 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Deploy to EC2 via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/naemeal-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/naemeal"

      - name: Upload application.properties
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/naemeal
            rm -f src/main/resources/application.properties
            echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: SSH and restart server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'naemeal' || true
            nohup java -jar /home/ubuntu/naemeal/naemeal-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
